# Generated by Django 5.1.4 on 2026-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
