# Generated by Django 5.1.4 on 2026-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_stagiaire_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
