# Generated by Django 5.1.4 on 2026-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_alter_stagiaire_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstagiaire',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
