# Generated by Django 5.1.4 on 2026-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_profilstagiaire_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstagiaire',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
