# Generated by Django 5.1.4 on 2025-11-07 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.TextField(default='inconnue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='courriel',
            field=models.EmailField(default='inconnue', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='nom',
            field=models.CharField(default='inconnue', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prenom',
            field=models.CharField(default='inconnue', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='inconnue', max_length=20),
            preserve_default=False,
        ),
    ]
