# Generated by Django 5.1.4 on 2026-04-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_profilstagiaire_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='signature',
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
