# Generated by Django 5.1.4 on 2026-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0006_remove_profilstagiaire_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilstagiaire',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Signature dessinée du responsable', null=True),
        ),
    ]
