# Generated by Django 5.1.4 on 2026-04-09 05:05

import siteweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_alter_profilstagiaire_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=siteweb.models.upload_to_client),
        ),
        migrations.AlterField(
            model_name='profilstagiaire',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
