# Generated by Django 5.1.4 on 2026-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0008_client_photo_alter_profilstagiaire_signature_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
