# Generated by Django 5.1.4 on 2026-04-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0010_remove_messageclient_date_reponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('type_projet', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devis/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
