# Generated by Django 5.1.4 on 2026-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0011_devis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='demande_rdv',
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='statut_rdv',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='aucun', max_length=20),
        ),
    ]
