# Generated by Django 5.1.4 on 2026-04-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0012_remove_profilstagiaire_demande_rdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstagiaire',
            name='message_stagiaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='reponse_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
