# Generated by Django 5.1.4 on 2026-05-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0015_rename_paypal_order_id_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='produit',
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='siteweb.facture')),
            ],
        ),
    ]
