# Generated by Django 5.1.4 on 2026-05-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0016_remove_facture_prix_remove_facture_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='adresse_client',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='code_postal_client',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='pays_client',
            field=models.CharField(default='Canada', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='ville_client',
            field=models.CharField(default='exite', max_length=100),
            preserve_default=False,
        ),
    ]
