# Generated by Django 5.1.4 on 2026-05-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0017_facture_adresse_client_facture_code_postal_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('entreprise', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('titre_projet', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('non_paye', 'Non payé')], default='non_paye', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
