# Generated by Django 5.1.4 on 2026-05-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0018_paiementclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoannonce',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
