# Generated by Django 5.1.4 on 2026-05-21 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0019_videoannonce_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='titre',
        ),
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projet',
            name='nom_projet',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('encours', 'En cours'), ('termine', 'Terminé')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='projet',
            name='technologie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
    ]
