# Generated by Django 5.1.4 on 2026-05-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0020_remove_projet_categorie_remove_projet_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstagiaire',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='horaire_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='horaire_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='pause_repas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='pointage_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='pointage_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilstagiaire',
            name='raison_absence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
