# Generated by Django 5.1.4 on 2026-05-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0021_profilstagiaire_absent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='horaire_entree',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='horaire_sortie',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='pause_repas',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='pointage_entree',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='pointage_sortie',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='raison_absence',
        ),
        migrations.CreateModel(
            name='PresenceStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('horaire_entree', models.TimeField(blank=True, null=True)),
                ('pause_repas', models.CharField(blank=True, max_length=100, null=True)),
                ('horaire_sortie', models.TimeField(blank=True, null=True)),
                ('pointage_entree', models.TimeField(blank=True, null=True)),
                ('pointage_sortie', models.TimeField(blank=True, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('raison_absence', models.TextField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='siteweb.profilstagiaire')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
