# Generated by Django 5.1.4 on 2026-05-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0022_remove_profilstagiaire_absent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
