# Generated by Django 5.1.4 on 2026-05-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0023_rapportmensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('fichier', models.FileField(upload_to='documents_stagiaires/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='siteweb.profilstagiaire')),
            ],
        ),
    ]
