# Generated by Django 5.1.4 on 2026-05-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0024_documentstagiaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='message_responsable',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='message_stagiaire',
        ),
        migrations.RemoveField(
            model_name='profilstagiaire',
            name='reponse_admin',
        ),
        migrations.CreateModel(
            name='MessageStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('stagiaire', 'Stagiaire'), ('admin', 'Administration')], max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='siteweb.profilstagiaire')),
            ],
        ),
    ]
