# Generated by Django 5.1.4 on 2026-06-08 03:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0025_remove_profilstagiaire_message_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoannonce',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
