# Generated by Django 5.1.4 on 2026-06-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0027_alter_videoannonce_video_groupestagiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroupestagiaire',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagegroupestagiaire',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagegroupestagiaire',
            name='supprime_par',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
