# Generated by Django 5.1.4 on 2026-06-24 19:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0028_messagegroupestagiaire_date_suppression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilstagiaire',
            name='attestation',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='attestations/'),
        ),
    ]
