# Generated by Django 5.1.4 on 2026-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0029_alter_profilstagiaire_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilstagiaire',
            name='attestation',
            field=models.FileField(blank=True, null=True, upload_to='attestations/'),
        ),
    ]
