# Generated by Django 5.1.4 on 2026-07-24 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0030_alter_profilstagiaire_attestation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_attestation', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de l’attestation')),
                ('numero_stagiaire', models.CharField(db_index=True, help_text='Exemple : STG-12345', max_length=20, verbose_name='Numéro du stagiaire')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('programme', models.CharField(max_length=200, verbose_name='Programme ou domaine du stage')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_delivrance', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Date de délivrance')),
                ('lieu_delivrance', models.CharField(default='Saguenay, Québec, Canada', max_length=150, verbose_name='Lieu de délivrance')),
                ('responsable', models.CharField(default='Diambere Kamara', max_length=150, verbose_name='Nom du responsable')),
                ('fonction_responsable', models.CharField(default='Directeur fondateur', max_length=150, verbose_name='Fonction du responsable')),
                ('signature_data', models.TextField(verbose_name='Signature électronique')),
                ('actif', models.BooleanField(default=True, verbose_name='Attestation active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_stage_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Attestation de stage',
                'verbose_name_plural': 'Attestations de stage',
                'ordering': ['-date_delivrance', '-id'],
            },
        ),
    ]
