# Generated by Django 5.1.4 on 2026-03-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0030_partenaire_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='affiches/')),
                ('actif', models.BooleanField(default=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='Lien YouTube ou vidéo')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
