# Generated by Django 5.1.4 on 2026-07-27 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0031_attestationstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('token_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('nom_entreprise', models.CharField(max_length=180, verbose_name='Nom de l’entreprise')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=40, verbose_name='Numéro de téléphone')),
                ('type_application', models.CharField(choices=[('restaurant', 'Application pour restaurant'), ('ecommerce', 'Site e-commerce'), ('marketplace', 'Marketplace multivendeur'), ('reservation', 'Application de réservation'), ('immobilier', 'Application immobilière'), ('sur_mesure', 'Application sur mesure')], max_length=30)),
                ('qualite', models.CharField(choices=[('essentiel', 'Essentiel'), ('professionnel', 'Professionnel'), ('premium', 'Premium')], max_length=30)),
                ('nom_application', models.CharField(blank=True, max_length=150)),
                ('nom_forfait', models.CharField(blank=True, max_length=100)),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('devise', models.CharField(default='CAD', max_length=10)),
                ('delai_estime', models.CharField(blank=True, max_length=100)),
                ('fonctionnalites', models.JSONField(blank=True, default=list)),
                ('budget_client', models.CharField(blank=True, max_length=100, verbose_name='Budget prévu')),
                ('delai_souhaite', models.CharField(blank=True, max_length=120, verbose_name='Délai souhaité')),
                ('description', models.TextField(blank=True, verbose_name='Description du projet')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle demande'), ('analyse', 'En analyse'), ('contacte', 'Client contacté'), ('devis', 'Devis envoyé'), ('acceptee', 'Demande acceptée'), ('refusee', 'Demande refusée')], default='nouvelle', max_length=20)),
                ('email_client_envoye', models.BooleanField(default=False)),
                ('email_hexaquebec_envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande d’application',
                'verbose_name_plural': 'Demandes d’applications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
