# Generated by Django 5.1.4 on 2026-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0031_affiche_videoannonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoannonce',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videoannonce',
            name='video',
            field=models.FileField(default=1, upload_to='videos_annonces/'),
            preserve_default=False,
        ),
    ]
