# Generated by Django 5.1.4 on 2026-09-01 23:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0032_demandeapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('entreprise', models.CharField(blank=True, max_length=180, verbose_name='Entreprise')),
                ('telephone', models.CharField(max_length=40, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse courriel')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet de la rencontre')),
                ('message', models.TextField(blank=True, verbose_name='Description du besoin')),
                ('date_souhaitee', models.DateTimeField(verbose_name='Date et heure souhaitées')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle demande'), ('confirmee', 'Conférence créée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=180)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('conference_creee_le', models.DateTimeField(blank=True, null=True)),
                ('email_envoye', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demande de conférence',
                'verbose_name_plural': 'Demandes de conférence',
                'ordering': ['-cree_le'],
            },
        ),
    ]
