# Generated by Django 5.1.4 on 2026-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0032_remove_videoannonce_video_url_videoannonce_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('vendeur_nom', models.CharField(max_length=200)),
                ('acheteur_nom', models.CharField(max_length=200)),
                ('produit', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
