# Generated by Django 5.1.4 on 2026-03-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0033_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='signature',
        ),
        migrations.AddField(
            model_name='facture',
            name='signature_vendeur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
