# Generated by Django 5.1.4 on 2026-09-30 00:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0033_demandeconference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Numéro du certificat')),
                ('numero_boutique', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Numéro de boutique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / boutique")),
                ('activite', models.CharField(max_length=255, verbose_name="Activité de l'entreprise")),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Adresse du site Web')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('date_delivrance', models.DateField(default=django.utils.timezone.now, verbose_name='Date de délivrance')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('REVOQUEE', 'Révoquée')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, default="HexaQuébec atteste que cette boutique numérique a été créée, configurée et mise en ligne avec l'accompagnement de HexaQuébec.", verbose_name="Texte de l'attestation")),
                ('est_protegee', models.BooleanField(default=True, verbose_name='Protection numérique HexaQuébec')),
                ('est_certifiee', models.BooleanField(default=True, verbose_name='Boutique certifiée')),
                ('code_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attestation boutique',
                'verbose_name_plural': 'Attestations boutiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
