# Generated by Django 5.1.4 on 2026-09-30 00:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0034_attestationboutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationboutique',
            name='date_signature',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='attestationboutique',
            name='fonction_signataire',
            field=models.CharField(default='Directeur technique et fondateur', max_length=200, verbose_name='Fonction du signataire'),
        ),
        migrations.AddField(
            model_name='attestationboutique',
            name='nom_signataire',
            field=models.CharField(default='Diambere Kamara', max_length=150, verbose_name='Nom du signataire'),
        ),
        migrations.AddField(
            model_name='attestationboutique',
            name='signature_electronique',
            field=models.ImageField(default=1, help_text='Signature électronique utilisée pour cette attestation.', upload_to='attestations/signatures/', verbose_name='Signature électronique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attestationboutique',
            name='tampon_electronique',
            field=models.ImageField(blank=True, null=True, upload_to='attestations/tampons/', verbose_name='Tampon électronique HexaQuébec'),
        ),
        migrations.AlterField(
            model_name='attestationboutique',
            name='code_verification',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code de vérification'),
        ),
        migrations.AlterField(
            model_name='attestationboutique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='attestationboutique',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
