# Generated by Django 5.1.4 on 2026-09-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0035_attestationboutique_date_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationboutique',
            name='signature_electronique',
            field=models.TextField(blank=True, verbose_name='Signature électronique dessinée'),
        ),
    ]
