# Generated by Django 5.1.4 on 2026-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0036_alter_attestationboutique_signature_electronique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAccompagnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_attestation', models.CharField(max_length=100)),
                ('nom_proprietaire', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nom_boutique', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=30)),
                ('whatsapp_confirme', models.BooleanField(default=False)),
                ('date_rendez_vous', models.DateField()),
                ('heure_rendez_vous', models.TimeField()),
                ('sujet', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('CONFIRMEE', 'Confirmée'), ('TRAITEE', 'Traitée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
