# Generated by Django 5.1.4 on 2026-03-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0036_rename_produit_cartitem_product_cart_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('shipped', 'Expédié')], default='pending', max_length=20),
        ),
    ]
