# Generated by Django 5.1.4 on 2026-10-05 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0037_demandeaccompagnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_avis', models.CharField(blank=True, max_length=50, unique=True)),
                ('numero_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=200)),
                ('entreprise_client', models.CharField(blank=True, max_length=200)),
                ('adresse_rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=150)),
                ('province_etat_region', models.CharField(blank=True, max_length=150)),
                ('code_postal', models.CharField(blank=True, max_length=30)),
                ('pays', models.CharField(max_length=150)),
                ('titre', models.CharField(max_length=255)),
                ('texte_avis', models.TextField()),
                ('date_avis', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
