# Generated by Django 5.1.4 on 2026-10-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0038_avisclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisclient',
            name='fonction_signataire',
            field=models.CharField(default='Directeur technique', max_length=150),
        ),
        migrations.AddField(
            model_name='avisclient',
            name='nom_signataire',
            field=models.CharField(default='Diambere Kamara', max_length=150),
        ),
        migrations.AddField(
            model_name='avisclient',
            name='signature_affichee',
            field=models.BooleanField(default=True),
        ),
    ]
