# Generated by Django 5.1.4 on 2026-10-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0039_avisclient_fonction_signataire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisclient',
            name='signature_affichee',
        ),
        migrations.AddField(
            model_name='avisclient',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature manuscrite enregistrée au format base64.'),
        ),
    ]
