# Generated by Django 5.1.4 on 2026-10-08 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0040_remove_avisclient_signature_affichee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreAcceptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lettre', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_personne', models.CharField(choices=[('STAGE', 'Stagiaire'), ('EMPLOYE', 'Employé')], max_length=20)),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(max_length=255, verbose_name='Fonction / poste')),
                ('etablissement_scolaire', models.CharField(blank=True, max_length=255, verbose_name='Établissement scolaire')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(blank=True, max_length=150)),
                ('province_region', models.CharField(blank=True, max_length=150, verbose_name='Province / région')),
                ('code_postal', models.CharField(blank=True, max_length=30)),
                ('pays', models.CharField(max_length=150)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_lettre', models.DateField(default=django.utils.timezone.now)),
                ('contenu_lettre', models.TextField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
