# Generated by Django 5.1.4 on 2026-10-10 01:46

import django.db.models.deletion
import django.utils.timezone
import siteweb.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0041_lettreacceptation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('REUNION', 'Réunion'), ('CONFERENCE', 'Conférence')], default='REUNION', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('debut', models.DateTimeField()),
                ('lien', models.URLField(blank=True, help_text='Lien HTTPS vers la visioconférence.')),
                ('domaine', models.CharField(blank=True, choices=[('WEB', 'Développement web'), ('MOBILE', 'Développement mobile'), ('IA', 'Intelligence artificielle'), ('COMMERCE', 'E-commerce'), ('MAINTENANCE', 'Maintenance informatique'), ('VENTE', 'Vente de services'), ('ADMINISTRATION', 'Administration'), ('MARKETING', 'Marketing et communication')], help_text='Vide = tous les domaines.', max_length=20)),
                ('annulee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'réunion ou conférence stagiaire',
                'verbose_name_plural': 'réunions et conférences stagiaires',
                'ordering': ['debut'],
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('titre', models.CharField(max_length=180)),
                ('contenu', models.TextField(help_text='Texte simple : les balises HTML sont affichées comme du texte.')),
                ('domaine', models.CharField(blank=True, choices=[('WEB', 'Développement web'), ('MOBILE', 'Développement mobile'), ('IA', 'Intelligence artificielle'), ('COMMERCE', 'E-commerce'), ('MAINTENANCE', 'Maintenance informatique'), ('VENTE', 'Vente de services'), ('ADMINISTRATION', 'Administration'), ('MARKETING', 'Marketing et communication')], help_text='Vide = tous les stagiaires.', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('publiee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'rubrique stagiaire',
                'verbose_name_plural': 'rubriques stagiaires',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=250)),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_espace_stagiaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification stagiaire',
                'verbose_name_plural': 'notifications stagiaires',
                'ordering': ['-cree', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Stagiaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=siteweb.models.nouveau_code, editable=False, max_length=40, unique=True)),
                ('domaine', models.CharField(choices=[('WEB', 'Développement web'), ('MOBILE', 'Développement mobile'), ('IA', 'Intelligence artificielle'), ('COMMERCE', 'E-commerce'), ('MAINTENANCE', 'Maintenance informatique'), ('VENTE', 'Vente de services'), ('ADMINISTRATION', 'Administration'), ('MARKETING', 'Marketing et communication')], max_length=20)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_espace_stagiaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil de l’espace stagiaire',
                'verbose_name_plural': 'profils de l’espace stagiaire',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('sortie', models.DateTimeField(blank=True, null=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='siteweb.stagiaires')),
            ],
            options={
                'verbose_name': 'pointage stagiaire',
                'verbose_name_plural': 'pointages stagiaires',
                'ordering': ['-entree'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=5000)),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('lu_admin', models.BooleanField(default=False)),
                ('lu_stagiaire', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_espace_stagiaires_emis', to=settings.AUTH_USER_MODEL)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='siteweb.stagiaires')),
            ],
            options={
                'verbose_name': 'message de l’espace stagiaire',
                'verbose_name_plural': 'messages de l’espace stagiaire',
                'ordering': ['cree', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagiaires',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gte', models.F('debut'))), name='hq_espace_dates_stage_valides'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(condition=models.Q(('sortie__isnull', True)), fields=('stagiaire',), name='hq_espace_un_pointage_ouvert'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.CheckConstraint(condition=models.Q(('sortie__isnull', True), ('sortie__gte', models.F('entree')), _connector='OR'), name='hq_espace_pointage_dates_valides'),
        ),
    ]
